/**
 * orval配置文件
 * 用于根据Swagger JSON生成标准化的TypeScript API文档及请求函数
 *
 * 配置参考: https://orval.dev/reference/configuration
 */
import { defineConfig } from 'orval';

export default defineConfig({
  qs: {
    /**
     * 输入配置
     * 指定Swagger JSON来源
     */
    input: {
      /** 后端OpenAPI 3.0文档地址 */
      target: 'http://localhost:18081/v3/api-docs',
    },

    /**
     * 输出配置
     * 控制生成代码的结构、格式和路径
     */
    output: {
      /** 工作根目录：所有生成产物统一存放位置 */
      workspace: 'src/api/generated',

      /** 汇总文件位置 */
      target: './index.ts',

      /** HTTP客户端类型 */
      client: 'axios',

      /** 代码生成模式：按tag拆分文件 */
      mode: 'tags',

      /** 模型(Schema)文件输出路径，相对于workspace */
      schemas: '../../types/modules',

      /** 每次生成前清理输出目录 */
      clean: true,

      /** 使用prettier格式化生成的代码 */
      prettier: true,

      /** 关闭barrel文件生成，避免不同tag间同名导出冲突 */
      indexFiles: false,

      /**
       * 自定义覆盖配置
       */
      override: {
        /**
         * 自定义mutator（请求函数）
         * 使用项目中的统一请求处理函数，集成axios实例和错误处理
         */
        mutator: {
          path: '../client/responseHandler.ts',
          name: 'handleResponse',
        },

        /**
         * 生成代码的头部注释
         */
        header: ({ info, title }) => [
          '// Code generated by orval. DO NOT EDIT.',
          `// 服务: ${title || 'API'}`,
          `// 版本: ${info?.version || '1.0.0'}`,
          `// 生成时间: ${new Date().toISOString()}`,
        ],
      },
    },
  },
});
