/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

/**
 * B端文章分页列表项
 */
export interface AdminArticleVO {
  /** 文章ID */
  id?: number;
  /** 博文标题 */
  articleTitle?: string;
  /** 封面 */
  articleCover?: string;
  /** 分类ID */
  categoryId?: number;
  /** 分类名称 */
  categoryName?: string;
  /** 标签ID */
  tagId?: number;
  /** 标签名称 */
  tagName?: string;
  /** 作者用户ID */
  userId?: number;
  /** 作者名称 */
  authorName?: string;
  /** 是否可见[0:否，1:是] */
  viewStatus?: boolean;
  /** 是否推荐[0:否，1:是] */
  recommendStatus?: boolean;
  /** 是否启用评论[0:否，1:是] */
  commentStatus?: boolean;
  /** 浏览量 */
  viewCount?: number;
  /** 点赞数 */
  likeCount?: number;
  /** 评论数 */
  commentCount?: number;
  /** 文章锁定提示 */
  tips?: string;
  /** 视频链接，列表不需要可删除 */
  videoUrl?: string;
  /** 是否有视频 */
  hasVideo?: boolean;
  /** 创建时间 */
  createTime?: string;
  /** 最终修改时间 */
  updateTime?: string;
  /** 最终修改人 */
  updateBy?: string;
}
