/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */
import type { AdminArticleVO } from './adminArticleVO';

/**
 * 后台文章分页响应结果
 */
export interface AdminArticlePageRespVO {
  /** 数据列表 */
  list?: AdminArticleVO[];
  /** 总条数 */
  total?: number;
  /** 总页数 */
  pages?: number;
  /** 当前页码 */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
}
