/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

/**
 * 后台文章分页查询请求参数
 */
export interface AdminArticlePageReqDTO {
  /**
   * 当前页码
   * @minimum 1
   */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
  /** 排序条件 */
  orderBy?: string;
  /** 文章标题模糊搜索关键词 */
  titleKey?: string;
  /** 分类ID，用于筛选 */
  cateId?: number;
  /** 标签ID，用于筛选 */
  tagId?: number;
  /** 是否推荐，null表示不筛选 */
  recommend?: boolean;
}
