/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

/**
 * 点赞请求参数
 */
export interface ArticleDTO {
  articleId?: number;
  userId?: number;
  operation?: number;
  commentId?: number;
}
