/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

/**
 * 文章分页查询参数
 */
export interface ArticlePageDTO {
  /**
   * 当前页码
   * @minimum 1
   */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
  /** 排序条件 */
  orderBy?: string;
  desc?: boolean;
  searchKey?: string;
  categoryId?: string;
  recommendStatus?: boolean;
  tagId?: number;
  articleSearch?: string;
}
