/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */
import type { Category } from './category';
import type { Tag } from './tag';

/**
 * 文章信息对象
 */
export interface ArticleVO {
  /** 文章ID */
  id?: number;
  /** 用户ID */
  userId?: number;
  /** 文章封面图片URL */
  articleCover?: string;
  /**
   * 文章标题
   * @minLength 1
   * @maxLength 200
   */
  articleTitle: string;
  /** 文章内容 */
  articleContent: string;
  /** 浏览次数 */
  viewCount?: number;
  /** 点赞次数 */
  likeCount?: number;
  /** 评论状态，true-开启，false-关闭 */
  commentStatus?: boolean;
  /** 推荐状态，true-推荐，false-不推荐 */
  recommendStatus?: boolean;
  /** 视频URL */
  videoUrl?: string;
  /** 文章密码，为空则不加密 */
  password?: string;
  /** 文章提示信息 */
  tips?: string;
  /** 可见状态，true-公开，false-私有 */
  viewStatus?: boolean;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 更新人 */
  updateBy?: string;
  /** 文章分类ID */
  categoryId: number;
  /** 文章标签ID */
  tagId: number;
  /** 评论数量 */
  commentCount?: number;
  /** 用户名 */
  username?: string;
  category?: Category;
  tag?: Tag;
  /** 是否包含视频，true-是，false-否 */
  hasVideo?: boolean;
}
