/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

export type AuditParams = {
/**
 * 审核状态: 1-通过 2-驳回
 */
status: number;
/**
 * 审核原因（驳回时必填
 */
auditReason?: string;
};
