/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

export type AuditParams = {
/**
 * 动态ID
 */
id: number;
/**
 * 审核状态: 1-通过 2-驳回
 */
status: number;
/**
 * 审核原因
 */
auditReason?: string;
};
