/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */
import type { Item } from './item';

/**
 * 作者评论列表 VO
 */
export interface AuthorCommentListVO {
  /** 总条数 */
  total?: number;
  /** 总页数 */
  pages?: number;
  /** 当前页码 */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
  /** 评论列表 */
  records?: Item[];
}
