/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */

/**
 * 查询参数
 */
export interface AuthorCommentQueryDTO {
  /** 页码，从1开始 */
  pageNum?: number;
  /** 每页条数，最大50 */
  pageSize?: number;
  /** 评论状态过滤：1=正常 2=禁言 3=审核中，不传则查全部 */
  status?: number;
  /** 评论内容关键词模糊搜索 */
  searchKey?: string;
}
