/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */
import type { BaseReqVORecordsItem } from './baseReqVORecordsItem';
import type { OrderItem } from './orderItem';
import type { PageObject } from './pageObject';

/**
 * 分页查询参数
 */
export interface BaseReqVO {
  records?: BaseReqVORecordsItem[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: PageObject;
  searchCount?: PageObject;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  order?: string;
  desc?: boolean;
  bizId?: number;
  commentType?: string;
  rootId?: number;
  searchKey?: string;
  articleSearch?: string;
  recommendStatus?: boolean;
  sortId?: number;
  labelId?: number;
  userStatus?: boolean;
  userType?: number;
  userId?: number;
  resourceType?: string;
  status?: boolean;
  classify?: string;
  pages?: number;
}
