/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

export type BatchListParams = {
/**
 * 字典类型编码列表，逗号分隔
 */
typeCodes: string;
};
