/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 文章分类信息
 */
export interface Category {
  id?: number;
  isDel?: number;
  createTime?: string;
  updateTime?: string;
  status?: number;
  isShow?: number;
  type?: number;
  name?: string;
  cateDesc?: string;
  sort?: number;
  icon?: string;
  updateBy?: string;
  createBy?: string;
}
