/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

/**
 * 分类列表VO
 */
export interface CategoryListVO {
  /** ID */
  id?: number;
  /** 分类名称 */
  name?: string;
  /** 分类描述 */
  desc?: string;
  /** 分类类型 */
  type?: number;
  /** 是否展示 */
  isShow?: number;
  /** 排序 */
  sort?: number;
  /** 图标 */
  icon?: string;
  /** 创建时间 */
  createTime?: string;
}
