/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

/**
 * 分类详情VO
 */
export interface CategoryDetailVO {
  /** ID */
  id?: number;
  /** 分类名称 */
  name?: string;
  /** 分类描述 */
  desc?: string;
  /** 分类类型: 0-导航栏分类, 1-普通分类 */
  type?: number;
  /** 是否展示: 0-否, 1-是 */
  isShow?: number;
  /** 排序 */
  sort?: number;
  /** 图标 */
  icon?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
}
