/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

export type ChangeUserTypeUserType = typeof ChangeUserTypeUserType[keyof typeof ChangeUserTypeUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeUserTypeUserType = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_2: '2',
} as const;
