/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */

export type ChangeUserStatus1Params = {
/**
 * 用户ID
 */
userId: number;
/**
 * 操作类型，true-解禁，false-封禁
 */
flag: boolean;
};
