/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */
import type { ChangeUserTypeUserType } from './changeUserTypeUserType';

export type ChangeUserTypeParams = {
/**
 * 用户ID
 */
userId: number;
/**
 * 用户类型，0-普通用户，1-管理员，2-超级管理员
 */
userType: ChangeUserTypeUserType;
};
