/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

export type ChangeArticleStatusParams = {
/**
 * 文章ID
 */
articleId: number;
/**
 * 可见状态，true-公开，false-私有
 */
viewStatus?: boolean;
/**
 * 评论状态，true-开启，false-关闭
 */
commentStatus?: boolean;
/**
 * 推荐状态，true-推荐，false-不推荐
 */
recommendStatus?: boolean;
};
