/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */
import type { Page } from './page';

/**
 * 评论信息对象
 */
export interface CommentVO {
  /** 评论ID */
  id?: number;
  /** 业务主键ID，如文章ID、树洞ID等 */
  bizId: number;
  /** 业务类型：1-文章 2-树洞留言 3-表白墙留言 */
  bizType: number;
  /** 父评论ID，0=根评论 */
  parentId?: number;
  /** 回复目标用户ID */
  replyToUserId?: number;
  /** 评论人ID */
  authorId?: number;
  /** 点赞数 */
  likeCnt?: number;
  /** 评论内容 */
  content: string;
  /** 顶级祖先评论ID，0=自身为根 */
  rootId?: number;
  /** 创建时间 */
  createTime?: string;
  childComments?: Page;
  /** 父评论用户名 */
  parentUsername?: string;
  /** 评论用户名 */
  username?: string;
  /** 用户头像URL */
  avatar?: string;
}
