/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

/**
 * 家庭卡片详情VO
 */
export interface FamilyDetailVO {
  /** ID */
  id?: number;
  /** 用户ID */
  userId?: number;
  /** 背景封面 */
  bgCover?: string;
  /** 男生头像 */
  manCover?: string;
  /** 女生头像 */
  womanCover?: string;
  /** 男生昵称 */
  manName?: string;
  /** 女生昵称 */
  womanName?: string;
  /** 计时 */
  timing?: string;
  /** 倒计时标题 */
  countdownTitle?: string;
  /** 倒计时时间 */
  countdownTime?: string;
  /** 额外信息 */
  familyInfo?: string;
  /** 是否启用 */
  status?: boolean;
  /** 点赞数 */
  likeCount?: number;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
}
