/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

export interface Family {
  id?: number;
  isDel?: number;
  createTime?: string;
  updateTime?: string;
  userId?: number;
  bgCover?: string;
  manCover?: string;
  womanCover?: string;
  manName?: string;
  womanName?: string;
  timing?: string;
  countdownTitle?: string;
  status?: boolean;
  countdownTime?: string;
  familyInfo?: string;
  likeCount?: number;
}
