/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

/**
 * 家庭卡片列表VO
 */
export interface FamilyListVO {
  /** ID */
  id?: number;
  /** 用户ID */
  userId?: number;
  /** 男生昵称 */
  manName?: string;
  /** 女生昵称 */
  womanName?: string;
  /** 计时 */
  timing?: string;
  /** 是否启用 */
  status?: boolean;
  /** 点赞数 */
  likeCount?: number;
  /** 创建时间 */
  createTime?: string;
}
