/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

/**
 * 家庭卡片公开列表VO
 */
export interface FamilyWebVO {
  /** ID */
  id?: number;
  /** 背景封面 */
  bgCover?: string;
  /** 男生昵称 */
  manName?: string;
  /** 女生昵称 */
  womanName?: string;
  /** 计时 */
  timing?: string;
  /** 点赞数 */
  likeCount?: number;
}
