/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 家庭卡片分页查询参数
 */
export interface FamilyPageQueryDTO {
  /** 状态：0-禁用, 1-启用 */
  status?: number;
  /** 页码 */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
}
