/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

export interface FileVO {
  type?: string;
  storeType?: string;
  relativePath?: string;
  absolutePath?: string;
  visitPath?: string;
  file?: Blob;
  originalName?: string;
}
