/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

export interface FileCreateReqVO {
  fileName?: string;
  filePath?: string;
  fileSize?: number;
  fileType?: string;
  storageType?: number;
  accessUrl?: string;
}
