/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

export type GetArticleWithPwdParams = {
/**
 * 文章ID
 */
id: number;
/**
 * 文章访问密码
 */
pwd?: string;
};
