/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

export type GetArticleByIdParams = {
/**
 * 文章ID
 */
id?: number;
/**
 * 文章ID（兼容 articleId 命名）
 */
articleId?: number;
/**
 * 文章密码（加密文章时必填）
 */
password?: string;
};
