/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

export type GetCodeForBindParams = {
/**
 * 手机号或邮箱
 */
place: string;
/**
 * 验证码类型，1-手机号验证码，2-邮箱验证码
 */
flag: number;
};
