/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */

export type GetCommentCountParams = {
/**
 * 来源ID，如文章ID、树洞ID等
 */
bizId: number;
/**
 * 来源类型，如article、treehole等
 */
type: string;
};
