/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

export type GetCaptchaParams = {
/**
 * 是否为注册，true-注册，false-其他
 */
flag: boolean;
/**
 * 邮箱地址
 */
email: string;
};
