/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

export type GetStateParams = {
/**
 * 业务ID
 */
bizId: number;
/**
 * 业务类型(1=文章,2=评论,6=分类,7=标签)
 */
bizType: number;
/**
 * 行为类型(1=点赞,2=点踩,3=订阅,4=转发,5=评论)
 */
action: number;
};
