/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 响应数据
 */
export interface GroupVO {
  id?: number;
  groupName?: string;
  avatar?: string;
  introduction?: string;
  groupType?: number;
  notice?: string;
  masterFlag?: boolean;
  adminFlag?: boolean;
  inType?: boolean;
  userStatus?: number;
  createTime?: string;
}
