/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */
import type { CategoryStatsVO } from './categoryStatsVO';

/**
 * 首页分类统计
 */
export interface HomeStatsVO {
  /** 文章总数 */
  articleTotal?: number;
  /** 分类总数 */
  categoryTotal?: number;
  /** 分类列表（含文章计数，已按排序值升序） */
  categories?: CategoryStatsVO[];
}
