/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */

export interface ImChatGroup {
  id?: number;
  groupName?: string;
  masterUserId?: number;
  groupType?: number;
  avatar?: string;
  introduction?: string;
  notice?: string;
  inType?: boolean;
  createTime?: string;
}
