/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

/**
 * 单条评论
 */
export interface Item {
  /** 评论ID */
  id?: number;
  /** 所属文章ID */
  bizId?: number;
  /** 评论内容 */
  content?: string;
  /** 评论人用户名 */
  username?: string;
  /** 评论人头像 */
  avatar?: string;
  /** 评论状态：1=正常 2=禁言 3=审核中 */
  status?: number;
  /** 直接子评论数量 */
  childCnt?: number;
  /** 创建时间 */
  createTime?: string;
}
