/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

export type ListTypeParams = {
/**
 * 类型名称（模糊查询）
 */
typeName?: string;
/**
 * 状态：0-禁用, 1-启用
 */
status?: number;
/**
 * 页码
 */
pageNum?: number;
/**
 * 每页条数
 */
pageSize?: number;
};
