/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

export type List4Params = {
/**
 * 分类类型过滤: 0-导航栏分类, 1-普通分类
 */
type?: number;
};
