/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

export type ListWeblinksParams = {
/**
 * 资源类型
 */
resourceType?: string;
/**
 * 分类
 */
classify?: string;
/**
 * 排序字段
 */
order?: string;
/**
 * 是否降序
 */
desc?: boolean;
/**
 * 页码
 */
pageNum?: number;
/**
 * 每页条数
 */
pageSize?: number;
};
