/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

export type Login1Params = {
/**
 * 登录账号（用户名、邮箱或手机号）
 */
account: string;
/**
 * 登录密码
 */
password: string;
/**
 * 是否为管理员登录，默认为false
 */
isAdmin?: boolean;
};
