/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

export type MailCodeParams = {
/**
 * 业务类型，如register、reset_password等
 */
bizType: string;
/**
 * 邮箱地址
 */
email: string;
};
