/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

export interface MomentMedia {
  id?: number;
  momentId?: number;
  fileId?: number;
  mediaType?: number;
  sortOrder?: number;
  createTime?: string;
}
