/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

/**
 * 动态分页查询参数
 */
export interface MomentPageQueryDTO {
  /** 用户ID */
  userId?: number;
  /** 状态: 0-草稿 1-正常 2-审核中 3-违规下架 */
  status?: number;
  /** 可见性: 0-私密 1-好友 2-公开 */
  visibility?: number;
  /** 来源: 1-本站 2-微信 3-QQ 4-微博 5-抖音 */
  source?: number;
  /**
   * 页码
   * @minimum 1
   */
  pageNum?: number;
  /**
   * 每页条数
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
}
