/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */
import type { MomentMedia } from './momentMedia';

export interface Moment {
  id?: number;
  isDel?: number;
  createTime?: string;
  updateTime?: string;
  userId?: number;
  content?: string;
  hasText?: boolean;
  hasImages?: boolean;
  hasVideos?: boolean;
  hasAudios?: boolean;
  likesCount?: number;
  commentsCount?: number;
  viewsCount?: number;
  status?: number;
  visibility?: number;
  source?: number;
  sourceExternalId?: string;
  sourceUserId?: string;
  delTime?: string;
  delBy?: number;
  auditReason?: string;
  auditedAt?: string;
  mediaList?: MomentMedia[];
}
