/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

/**
 * 媒体文件VO
 */
export interface MomentMediaVO {
  /** ID */
  id?: number;
  /** 文件ID */
  fileId?: number;
  /** 媒体类型: 1-图片 2-视频 3-音频 */
  mediaType?: number;
  /** 排序权重 */
  sortOrder?: number;
  /** 文件URL */
  url?: string;
}
