/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */
import type { MediaItem } from './mediaItem';

/**
 * 动态数据
 */
export interface MomentSaveReqDTO {
  /** 动态ID（更新时传入，发布时不传） */
  id?: number;
  /** 纯文本内容 */
  content?: string;
  /**
   * 媒体文件ID列表（已废弃，请使用 mediaList）
   * @deprecated
   */
  mediaIds?: number[];
  /** 可见性: 0-私密 1-好友 2-公开，默认2 */
  visibility?: number;
  /** 媒体文件列表（含类型与排序） */
  mediaList?: MediaItem[];
}
