/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

/**
 * 动态列表VO
 */
export interface MomentListVO {
  /** ID */
  id?: number;
  /** 发布者ID */
  userId?: number;
  /** 内容摘要（截取前50字） */
  contentSummary?: string;
  /** 是否有图片 */
  hasImages?: boolean;
  /** 是否有视频 */
  hasVideos?: boolean;
  /** 是否有音频 */
  hasAudios?: boolean;
  /** 点赞数 */
  likesCount?: number;
  /** 评论数 */
  commentsCount?: number;
  /** 浏览数 */
  viewsCount?: number;
  /** 状态: 0-草稿 1-正常 2-审核中 3-违规下架 */
  status?: number;
  /** 可见性: 0-私密 1-好友 2-公开 */
  visibility?: number;
  /** 来源: 1-本站 2-微信 3-QQ 4-微博 5-抖音 */
  source?: number;
  /** 创建时间 */
  createTime?: string;
}
