/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */
import type { MomentMediaVO } from './momentMediaVO';

/**
 * 动态详情VO
 */
export interface MomentDetailVO {
  /** ID */
  id?: number;
  /** 发布者ID */
  userId?: number;
  /** 纯文本内容 */
  content?: string;
  /** 是否有文本 */
  hasText?: boolean;
  /** 是否有图片 */
  hasImages?: boolean;
  /** 是否有视频 */
  hasVideos?: boolean;
  /** 是否有音频 */
  hasAudios?: boolean;
  /** 点赞数 */
  likesCount?: number;
  /** 评论数 */
  commentsCount?: number;
  /** 浏览数 */
  viewsCount?: number;
  /** 状态: 0-草稿 1-正常 2-审核中 3-违规下架 */
  status?: number;
  /** 可见性: 0-私密 1-好友 2-公开 */
  visibility?: number;
  /** 来源: 1-本站 2-微信 3-QQ 4-微博 5-抖音 */
  source?: number;
  /** 三方平台原始动态ID */
  sourceExternalId?: string;
  /** 三方平台用户ID */
  sourceUserId?: string;
  /** 删除时间 */
  delTime?: string;
  /** 删除操作人ID */
  delBy?: number;
  /** 审核/驳回原因 */
  auditReason?: string;
  /** 审核时间 */
  auditedAt?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 媒体文件列表 */
  mediaList?: MomentMediaVO[];
}
