/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */
import type { MomentMediaVO } from './momentMediaVO';

/**
 * 动态详情VO
 */
export interface MomentDetailVO {
  /** ID */
  id?: number;
  /** 发布者ID */
  userId?: number;
  /** 发布者昵称 */
  authorName?: string;
  /** 发布者头像URL */
  authorAvatar?: string;
  /** 纯文本内容 */
  content?: string;
  /** 是否有文本 */
  hasText?: boolean;
  /** 是否有图片 */
  hasImages?: boolean;
  /** 是否有视频 */
  hasVideos?: boolean;
  /** 是否有音频 */
  hasAudios?: boolean;
  /** 点赞数 */
  likesCount?: number;
  /** 评论数 */
  commentsCount?: number;
  /** 浏览数 */
  viewsCount?: number;
  /** 可见性: 0-私密 1-好友 2-公开 */
  visibility?: number;
  /** 来源: 1-本站 2-微信 3-QQ 4-微博 5-抖音 */
  source?: number;
  /** 当前用户是否已点赞 */
  liked?: boolean;
  /** 媒体文件列表 */
  mediaList?: MomentMediaVO[];
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
}
