/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */
import type { FamilyPageQueryDTO } from './familyPageQueryDTO';

export type PageList3Params = {
query: FamilyPageQueryDTO;
};
