/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */
import type { PageRecordsItem } from './pageRecordsItem';
import type { OrderItem } from './orderItem';
import type { PageObject } from './pageObject';

/**
 * 子评论分页列表
 */
export interface Page {
  records?: PageRecordsItem[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: PageObject;
  searchCount?: PageObject;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  pages?: number;
}
