/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

export type PageList1Params = {
/**
 * 分类ID
 */
categoryId?: number;
/**
 * 关键词（模糊匹配名称）
 */
keyword?: string;
/**
 * 页码
 */
pageNum?: number;
/**
 * 每页条数
 */
pageSize?: number;
};
