/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */
import type { PageObjectRecordsItem } from './pageObjectRecordsItem';
import type { OrderItem } from './orderItem';
import type { PageObject as __PageObject } from './pageObject';

export interface PageObject {
  records?: PageObjectRecordsItem[];
  total?: number;
  size?: number;
  current?: number;
  orders?: OrderItem[];
  optimizeCountSql?: __PageObject;
  searchCount?: __PageObject;
  optimizeJoinOfCountSql?: boolean;
  maxLimit?: number;
  countId?: string;
  pages?: number;
}
