/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */
import type { SysDictType } from './sysDictType';

/**
 * 分页结果统一返回类
 */
export interface PageResultSysDictType {
  /** 数据列表 */
  list?: SysDictType[];
  /** 总条数 */
  total?: number;
  /** 总页数 */
  pages?: number;
  /** 当前页码 */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
}
