/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */
import type { PageResultObjectListItem } from './pageResultObjectListItem';

/**
 * 分页结果统一返回类
 */
export interface PageResultObject {
  /** 数据列表 */
  list?: PageResultObjectListItem[];
  /** 总条数 */
  total?: number;
  /** 总页数 */
  pages?: number;
  /** 当前页码 */
  pageNum?: number;
  /** 每页条数 */
  pageSize?: number;
}
