/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

export type ResetPwdForFgtPwdParams = {
/**
 * 邮箱地址
 */
email: string;
/**
 * 业务类型
 */
bizType: string;
/**
 * 验证码
 */
code: string;
/**
 * 新密码
 */
password: string;
};
