/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */
import type { TagWebVO } from './tagWebVO';

/**
 * 公共响应类
 */
export interface RListTagWebVO {
  /** 状态码：200-成功，其他-失败 */
  code?: number;
  /** 业务消息 */
  msg?: string;
  /** 响应数据 */
  data?: TagWebVO[];
  /** 服务器时间戳 */
  currentTimeMillis?: number;
}
