/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

/**
 * 响应数据
 */
export type RListMapStringObjectDataItem = {[key: string]: { [key: string]: unknown }};
