/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */
import type { User } from './user';

/**
 * 公共响应类
 */
export interface RListUser {
  /** 状态码：200-成功，其他-失败 */
  code?: number;
  /** 业务消息 */
  msg?: string;
  /** 响应数据 */
  data?: User[];
  /** 服务器时间戳 */
  currentTimeMillis?: number;
}
