/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */
import type { SysDictDataVO } from './sysDictDataVO';

/**
 * 响应数据
 */
export type RMapStringListSysDictDataVOData = {[key: string]: SysDictDataVO[]};
