/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */
import type { RMapStringObjectData } from './rMapStringObjectData';

/**
 * 公共响应类
 */
export interface RMapStringObject {
  /** 状态码：200-成功，其他-失败 */
  code?: number;
  /** 业务消息 */
  msg?: string;
  /** 响应数据 */
  data?: RMapStringObjectData;
  /** 服务器时间戳 */
  currentTimeMillis?: number;
}
