/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */
import type { MomentDetailVO } from './momentDetailVO';

/**
 * 公共响应类
 */
export interface RMomentDetailVO {
  /** 状态码：200-成功，其他-失败 */
  code?: number;
  /** 业务消息 */
  msg?: string;
  data?: MomentDetailVO;
  /** 服务器时间戳 */
  currentTimeMillis?: number;
}
