/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

export type Subscribe1Params = {
/**
 * 专栏ID
 */
categoryId: number;
/**
 * 订阅状态，true-订阅，false-取消订阅
 */
flag: boolean;
};
