/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 系统配置信息
 */
export interface SysConfig {
  id?: number;
  configName?: string;
  configKey?: string;
  configValue?: string;
  configType?: string;
}
