/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 字典类型请求
 */
export interface SysDictTypeReq {
  /** 字典类型ID（编辑时传入） */
  id?: number;
  /** 字典类型编码 */
  typeCode: string;
  /** 字典类型名称 */
  typeName: string;
  /** 状态：0-禁用, 1-启用 */
  status?: number;
  /** 排序权重 */
  sort?: number;
  /** 备注 */
  remark?: string;
}
