/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-18T20:48:49.307Z
 */

/**
 * 响应数据
 */
export interface SysDictData {
  id?: number;
  isDel?: number;
  createTime?: string;
  updateTime?: string;
  typeCode?: string;
  itemCode?: string;
  itemValue?: string;
  itemLabel?: string;
  sort?: number;
  remark?: string;
  status?: number;
  isDefault?: number;
}
