/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 字典数据VO
 */
export interface SysDictDataVO {
  /** 字典项编码 */
  itemCode?: string;
  /** 字典项实际存储值 */
  itemValue?: string;
  /** 字典项显示标签 */
  itemLabel?: string;
  /** 排序值 */
  sort?: number;
}
