/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

/**
 * 字典数据请求
 */
export interface SysDictDataReq {
  /** 字典数据ID（编辑时传入） */
  id?: number;
  /** 字典类型编码 */
  typeCode: string;
  /** 字典项编码 */
  itemCode: string;
  /** 字典项实际存储值 */
  itemValue?: string;
  /** 字典项显示标签 */
  itemLabel: string;
  /** 排序值 */
  sort?: number;
  /** 状态：0-禁用, 1-启用 */
  status?: number;
  /** 是否默认值：0-否, 1-是 */
  isDefault?: number;
  /** 备注 */
  remark?: string;
}
