/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

/**
 * 响应数据
 */
export interface SysDictType {
  id?: number;
  isDel?: number;
  createTime?: string;
  updateTime?: string;
  typeCode?: string;
  typeName?: string;
  status?: number;
  remark?: string;
  sort?: number;
  createBy?: string;
  updateBy?: string;
}
