/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

/**
 * 文章标签信息
 */
export interface Tag {
  id?: number;
  isDel?: number;
  createTime?: string;
  updateTime?: string;
  categoryId?: number;
  name?: string;
  tagDesc?: string;
  sort?: number;
  createBy?: string;
  updateBy?: string;
}
