/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 响应数据
 */
export interface TagDictVO {
  /** 字典项实际存储值 */
  value?: string;
  /** 字典项显示标签 */
  label?: string;
  /** 排序值 */
  sort?: number;
  cateId?: number;
}
