/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

/**
 * 标签详情VO
 */
export interface TagDetailVO {
  /** ID */
  id?: number;
  /** 分类ID */
  categoryId?: number;
  /** 标签名称 */
  name?: string;
  /** 标签描述 */
  desc?: string;
  /** 分类名称 */
  categoryName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
}
