/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-05T08:15:14.299Z
 */

/**
 * 标签请求
 */
export interface TagSaveReqDTO {
  /** ID（编辑时传入） */
  id?: number;
  /** 所属分类ID */
  categoryId: number;
  /** 标签名称 */
  name: string;
  /** 标签描述 */
  desc?: string;
}
