/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

export type UpdateSecretInfoParams = {
/**
 * 原手机号、原邮箱或原密码
 */
place: string;
/**
 * 更新类型，1-手机号，2-邮箱，3-密码
 */
flag: number;
/**
 * 验证码（更新手机号或邮箱时必填）
 */
code?: string;
/**
 * 新手机号、新邮箱或新密码
 */
password: string;
};
