/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

export type UpdateForForgetPasswordParams = {
/**
 * 手机号或邮箱
 */
place: string;
/**
 * 验证类型，1-手机号，2-邮箱
 */
flag: number;
/**
 * 验证码
 */
code: string;
/**
 * 新密码
 */
password: string;
};
