/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

/**
 * 响应数据
 */
export interface UserFriendVO {
  id?: number;
  userId?: number;
  friendId?: number;
  username?: string;
  gender?: number;
  avatar?: string;
  introduction?: string;
  friendStatus?: number;
  remark?: string;
  createTime?: string;
}
