/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */

/**
 * 响应数据
 */
export interface User {
  id?: number;
  isDel?: number;
  createTime?: string;
  updateTime?: string;
  username?: string;
  password?: string;
  phoneNumber?: string;
  email?: string;
  userStatus?: number;
  gender?: number;
  openId?: string;
  avatar?: string;
  admire?: string;
  subscribe?: string;
  introduction?: string;
  userType?: number;
  updateBy?: string;
}
