/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-21T17:12:14.856Z
 */

/**
 * 性别，0-未知，1-男，2-女
 */
export type UserVOGender = typeof UserVOGender[keyof typeof UserVOGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserVOGender = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
