/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-08-14T17:42:28.123Z
 */
import type { UserVOGender } from './userVOGender';

/**
 * 用户注册信息
 */
export interface UserVO {
  /** 用户ID */
  id?: number;
  /** 用户名 */
  username: string;
  /** 手机号码 */
  phoneNumber?: string;
  /** 邮箱地址 */
  email?: string;
  /** 密码 */
  password: string;
  /** 性别，0-未知，1-男，2-女 */
  gender?: UserVOGender;
  /** 头像URL */
  avatar?: string;
  /** 个人简介 */
  introduction?: string;
  /** 订阅的标签ID列表，以逗号分隔 */
  subscribe?: string;
  /** 创建时间 */
  createTime?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 更新人 */
  updateBy?: string;
  /** 是否为管理员 */
  isBoss?: boolean;
  /** 访问令牌 */
  accessToken?: string;
  /** 验证码 */
  code?: string;
}
