/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-09-06T09:54:17.227Z
 */

/**
 * 网站信息对象
 */
export interface WebInfo {
  id?: number;
  webName?: string;
  webTitle?: string;
  notices?: string;
  footer?: string;
  backgroundImage?: string;
  avatar?: string;
  randomAvatar?: string;
  randomName?: string;
  randomCover?: string;
  waifuJson?: string;
  status?: boolean;
  historyAllCount?: string;
  historyDayCount?: string;
  defaultStoreType?: string;
}
