/**
 * // Code generated by orval. DO NOT EDIT.
 * // 服务: Openapi在线JSON文档
 * // 版本: 1.0.0
 * // 生成时间: 2026-10-02T22:09:17.856Z
 */

/**
 * 友链信息对象
 */
export interface WeblinksVO {
  id?: number;
  title?: string;
  classify?: string;
  cover?: string;
  url?: string;
  type?: string;
  remark?: string;
  status?: boolean;
  introduction?: string;
  createTime?: string;
}
